version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql123
      - MYSQL_ROOT_PASSWORD=mysql
    restart: always
    volumes:
       - ./dbdata:/var/lib/mysql

volumes:
    dbdata:
